<?php
require('TCPDF/tcpdf.php');
require('phpqrcode/qrlib.php'); // Include the QR Code library

// Assuming you have a valid database connection already
$cn = mysqli_connect("localhost", "root", "", "db_admission");

if (!$cn) {
    die("Connection failed: " . mysqli_connect_error());
}

$sql = "SELECT * FROM transactions WHERE id = " . $_GET['id'];
$table = mysqli_query($cn, $sql);

if ($table) {
    $row = mysqli_fetch_assoc($table);

    // Assuming these variables are defined somewhere in your code
    $sname = $row['student_name'];
    $gname = $row['guardian_name'];
    $contact = $row['contact'];
    $email = $row['email'];
    $address = $row['address'];
    $District = $row['district'];
    $Pincode = $row['pincode'];
    $State = $row['state'];
    $class = $row['class'];
    $shift = $row['shift'];
    $Caste = $row['caste'];

    // Create PDF instance
    $pdf = new TCPDF();

    // Set document information
    $pdf->SetCreator(PDF_CREATOR);
    $pdf->SetAuthor('Name School');
    $pdf->SetTitle('Admission Form');

    // Add a page
    $pdf->AddPage();

    // Set font
    $pdf->SetFont('helvetica', 'B', 14);

    // Output school details in the PDF
    $pdf->writeHTML('<h3>XYZ SCHOOL</h3><p>XYZ ADDRESS, NAME OF CITY.</p><hr>', true, false, true, false, 'C');

    // Set font for the text after the photo
    $pdf->SetFont('helvetica', '', 12);

    // Output student details in the PDF
    $pdf->Ln(30); // Add vertical space
    $pdf->Cell(0, 10, 'Student Name: ' . $sname, 0, 1);
    $pdf->Cell(0, 10, 'Guardian Name: ' . $gname, 0, 1);
    $pdf->Cell(0, 10, 'Contact: ' . $contact, 0, 1);
    $pdf->Cell(0, 10, 'Email: ' . $email, 0, 1);
    $pdf->Cell(0, 10, 'Address: ' . $address, 0, 1);
    $pdf->Cell(0, 10, 'District: ' . $District, 0, 1);
    $pdf->Cell(0, 10, 'Pincode: ' . $Pincode, 0, 1);
    $pdf->Cell(0, 10, 'State: ' . $State, 0, 1);
    $pdf->Cell(0, 10, 'Class: ' . $class, 0, 1);
    $pdf->Cell(0, 10, 'Shift: ' . $shift, 0, 1);
    $pdf->Cell(0, 10, 'Caste: ' . $Caste, 0, 1);
    $pdf->Ln(2);

    // Add QR Code image to the PDF
//     $qrCodeData = "Your QR Code Data Here"; // Replace with the actual QR code data
//     $qrCodePath = 'path/to/save/qr-code.png'; // Specify the path to save the QR code image
//     QRcode::png($qrCodeData, $qrCodePath);
//     $pdf->Image($qrCodePath, $pdf->GetX(), $pdf->GetY(), 30, 30, '', '', '', true, 300);
//     $pdf->SetX($pdf->GetX() + 40); // Move the cursor to the right to leave space for the QR Code

    // Add note to the PDF
    $note = '<h5>NOTE:</h5><br><p>Please call in school Admission Dept.<br>Enquiry for your fee Structure<br>Payment Pay above QRcode<br>
    Addmission Contant =xxxxxxxx77<br><br><br>This form is generated by computer therefore nobody no necessary Signature of the head of school</p>';
    $pdf->Ln(40);
    $pdf->writeHTML($note, true, false, true, false, 'C');

    // Output the PDF to the browser
    $pdf->Output('admission_form.pdf', 'D');

} else {
    echo '<span>' . mysqli_error($cn) . '</span>';
}

mysqli_close($cn);
?>
